@startmindmap
<style>
mindmapDiagram {
.green {
    BackgroundColor lightgreen
}
.rose {
    BackgroundColor #FFBBCC
}
.style_color_blue {
    BackgroundColor lightblue
}
}
</style>
caption 超级电容逻辑
title 超级电容
* <&flag>电容
** <&globe>跳帽1-2短接
*** 电源上电，关机后，会自动开机。
*** 非法断电，可以正常关机。不再开机。
*** 电源上电，电容电量不满的时候，电容会充电。

** <&star>跳帽2-3短接
*** 电源断电，电容启动时候，会检测到是否开机，如果不开机，则会开机
*** 电源上电，电容电量不满的时候，电容会充电。

** 功能需求
*** 插上电源，可以自动开机，保持不关机。
*** 非法断电，可以正常关机。不再开机。
***[#FFBBCC]  正常关机，可以关机，不在开机。
***[#FFBBCC]  需要能正常的控制开机，使用BIOS自启动方式来开机。\n不能经过超级电容来控制开机的信号。

** 实现方式
*** 一直保持住监听 S 信号。当有信号变化时候，\n 则发送给电脑 Power Button 信号。
***[#FFBBCC] 检测到电脑发送过来的信号后，并验证有 12V 电压的情况下，\n则不在发送给电脑 Power Button 信号。

** 功能梳理
*** 管理 LED 灯的亮灭，有两种颜色，红色和绿色。\n是电源管理芯片控制的吗？
*** 电容管理，是电源管理芯片控制，程序是芯片自带的原厂的程序？
*** 检测到电脑 12V 电压变化，发送给电脑 Power Button 信号。
*** 电容的电量保持到不能低于多少时候，则关闭放电。
*** 电容的电量暴多到低于多少的时候，则不开机处理。保护电容的电。
*** 电容的充电和放电的控制。是什么条件触发的？\n是哪个芯片控制的？- 插上即充电，断开即放电。 <<style_color_blue>>
header
超级电容逻辑图
endheader
center footer 超级电容逻辑图
@endmindmap