
@startuml
participant 人脸请求 as Font
participant 人脸回调 as BACK
title 添加人脸扫脸和响应状态流转
autonumber
Font -> BACK: STATUS = IVFACE_STATUS_STANDBY 3 \n create: SENSETIME_CMD_RESET \n req:IVFACE_REQ_ENROLL \n dir: SSFACE_DIRECTION_NONE 0 
note left: 初始化

Font -> BACK: STATUS = IVFACE_STATUS_ENROLL 5 \n create: SENSETIME_CMD_ENROLL \n req:IVFACE_REQ_ENROLL  \n dir: SSFACE_DIRECTION_MIDDLE 0x1 
note left: 准备发送第一次请求 正脸

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_RIGHT 0x2 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向右微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_LEFT 0x4 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向左微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_DOWN 0x8 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向下微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_UP 0x10 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向上微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n 回调 \n 设置状态为空闲状态   
note left: 接收到的命令 \n 状态是0 



@enduml