
@startuml
participant 雷达识别 as Radar
participant 人脸识别 as Face
participant 前板 as Font
participant 后板 as BACK
title 通过人脸识别开锁流程
autonumber
Radar -> Radar: iviews_radar_status_changed_callback \nstatus:1
note left: 雷达识别成功 \n回调函数

Radar -> Face: iviews_face_verify_resp_handle \n create: SENSETIME_CMD_ENROLL \n req:IVFACE_REQ_ENROLL  \n dir: SSFACE_DIRECTION_MIDDLE 0x1 
note left: 人脸识别

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  ivlock_front_verify_driver_action_handle \n FOR :1 \nIVLOCK_ADD_KEY_REQ_CANCEL_BACK \n
note left: 配网模式中

BACK -> Font:  IVLOCK_CMD_ADD_KEY_REQ \nIVLOCK_ADD_KEY_REQ_CANCEL_BACK 退出配网模式
note left: 配网模式中



BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_LEFT 0x4 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向左微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_DOWN 0x8 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向下微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5
note left: 接收到的命令

Font -> BACK:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n SENSETIME_CMD_ENROLL \n dir: SSFACE_DIRECTION_UP 0x10 
note left: 如果步骤不是 0 \n则继续验证人脸 \n发送向上微微转头

BACK -> Font:  SENSETIME_CMD_ENROLL \n -> iviews_face_enroll_resp_handle \n STATUS = IVFACE_STATUS_ENROLL 5 \n 回调 \n 设置状态为空闲状态   
note left: 接收到的命令 \n 状态是0 



@enduml