
@startuml

skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

title "电容开关状态图"
skinparam componentStyle uml2

cloud {
    interface "Button_Task" as button_task
    interface "Button_Send" as api
    interface "Storage" as storage
    interface "Transform" as transform
    interface "Publisher" as publisher
    interface "Website" as website

    button_task - [Button_Task]

    website - [Button_Change]
    [Button_Change] .up.> button_task
    [Button_Change] .down.> storage
    [Button_Change] .right.> api

    api - [Orchestra]
    transform - [Orchestra]
    publisher - [Orchestra]
    [Orchestra] .up.> button_task
    [Orchestra] .down.> storage

    [Transform] .up.> button_task
    [Transform] .down.> storage
    [Transform] ..> transform

    [Publisher] .up.> button_task
    [Publisher] .down.> storage
    [Publisher] ..> publisher

    storage - [Storage]
    [Storage] .up.> button_task
}

@enduml